using System.Collections.Generic;
using System.Linq;

namespace Lumia
{
    // Generated from saved reference tooltips; conditional and delayed effects were manually reviewed.
    public static class StatusIdentity
    {
        public static void Configure(List<CardDef> cards)
        {
            var table=new Dictionary<string,List<CardStatusRule>>();
            Add(table,"nia_w","pull");
            Add(table,"nia_w","slow", need:"blocks", count:1);
            Add(table,"nia_r","stun");
            Add(table,"jackie_w","slow", timing:"next_basic");
            Add(table,"aya_r","fear");
            Add(table,"hyunwoo_q","slow");
            Add(table,"hyunwoo_e","stun");
            Add(table,"hyunwoo_e","knockback");
            Add(table,"hyunwoo_r","stun");
            Add(table,"hyunwoo_r","knockback");
            Add(table,"hyunwoo_r","armor_break");
            Add(table,"yuki_q","slow");
            Add(table,"yuki_q","stun", need:"cuff", count:1);
            Add(table,"hyejin_w","slow");
            Add(table,"hyejin_w","pull", timing:"charm");
            Add(table,"sua_q","slow");
            Add(table,"sua_q","stun", need:"bookmark", count:1);
            Add(table,"sua_w","blind");
            Add(table,"sua_e","slow");
            Add(table,"sua_e","airborne", need:"bookmark", count:1);
            Add(table,"isol_q","root", timing:"semtex");
            Add(table,"nadine_w","slow", timing:"trap");
            Add(table,"nadine_r","slow", timing:"wolf");
            Add(table,"emma_q","slow", need:"dove", count:1);
            Add(table,"emma_e","polymorph");
            Add(table,"emma_e","slow");
            Add(table,"charlotte_q","slow");
            Add(table,"nathapon_w","slow");
            Add(table,"nathapon_w","root", timing:"last_frame");
            Add(table,"nathapon_e","slow");
            Add(table,"nathapon_e","knockback", timing:"next_basic");
            Add(table,"nicky_q","knockback");
            Add(table,"nicky_w","slow");
            Add(table,"nicky_e","slow");
            Add(table,"nicky_e","stun", need:"guard_ready", count:1);
            Add(table,"nicky_r","airborne");
            Add(table,"daniel_q","slow");
            Add(table,"daniel_w","slow");
            Add(table,"daniel_r","silence");
            Add(table,"tia_q","slow");
            Add(table,"tia_r","stun");
            Add(table,"laura_w","slow");
            Add(table,"laura_e","airborne");
            Add(table,"lenox_w","slow");
            Add(table,"lenox_w","pull");
            Add(table,"lenox_e","slow");
            Add(table,"lenox_e","pull");
            Add(table,"leon_e","airborne");
            Add(table,"leon_r","airborne");
            Add(table,"leon_r","knockback");
            Add(table,"rozzi_w","heal_reduction");
            Add(table,"rozzi_w","armor_break");
            Add(table,"rozzi_e","stun");
            Add(table,"rozzi_r","slow", timing:"semtex_fuse");
            Add(table,"luke_q","armor_break");
            Add(table,"luke_e","slow");
            Add(table,"luke_r","slow");
            Add(table,"dailin_e","slow");
            Add(table,"dailin_r","suppression");
            Add(table,"rio_w","slow");
            Add(table,"rio_r","slow", need:"bow", count:1);
            Add(table,"rio_r","stun", need:"bow", count:0, exact:true);
            Add(table,"rio_r","knockback", need:"bow", count:0, exact:true);
            Add(table,"martina_e","slow");
            Add(table,"martina_e","stun", need:"record", count:3);
            Add(table,"martina_r","stun", need:"record", count:3);
            Add(table,"mai_q","slow", need:"pin", count:1);
            Add(table,"mai_e","taunt");
            Add(table,"markus_w","airborne");
            Add(table,"markus_e","knockback");
            Add(table,"markus_r","slow");
            Add(table,"markus_r","airborne");
            Add(table,"markus_r","knockback");
            Add(table,"markus_r","armor_break");
            Add(table,"magnus_q","slow");
            Add(table,"magnus_e","stun", need:"wall_pressure", count:1);
            Add(table,"vanya_e","slow");
            Add(table,"vanya_r","slow");
            Add(table,"vanya_r","sleep", timing:"sleep_fuse");
            Add(table,"barbara_e","stun");
            Add(table,"barbara_r","slow");
            Add(table,"barbara_r","stun");
            Add(table,"bernice_q","slow");
            Add(table,"bernice_w","root", timing:"foothold");
            Add(table,"bernice_r","root");
            Add(table,"bianca_q","root");
            Add(table,"bianca_r","slow");
            Add(table,"celine_r","slow");
            Add(table,"sho_e","slow");
            Add(table,"sho_e","airborne");
            Add(table,"sho_e","knockback");
            Add(table,"sho_r","slow");
            Add(table,"sho_r","heal_reduction");
            Add(table,"shoichi_e","slow");
            Add(table,"sissela_e","stun");
            Add(table,"silvia_w","slow");
            Add(table,"silvia_w","airborne");
            Add(table,"silvia_e","knockback");
            Add(table,"adela_q","stun", need:"pawn", count:3);
            Add(table,"adela_w","airborne");
            Add(table,"adela_e","slow");
            Add(table,"adriana_w","slow");
            Add(table,"adriana_e","slow");
            Add(table,"adina_q","stun", need:"sign", count:1, exact:true);
            Add(table,"adina_w","slow");
            Add(table,"adina_w","stun", need:"sign", count:1, exact:true);
            Add(table,"adina_e","stun", need:"sign", count:1, exact:true);
            Add(table,"isaac_e","stun");
            Add(table,"isaac_r","slow");
            Add(table,"alex_e","slow");
            Add(table,"alex_r","slow");
            Add(table,"jan_q","slow");
            Add(table,"jan_q","airborne");
            Add(table,"jan_w","stun");
            Add(table,"jan_w","knockback");
            Add(table,"jan_r","slow");
            Add(table,"jan_r","knockback");
            Add(table,"estelle_q","stun", timing:"next_basic");
            Add(table,"estelle_w","slow");
            Add(table,"estelle_e","knockback");
            Add(table,"estelle_r","slow", timing:"helitack");
            Add(table,"estelle_r","airborne", timing:"helitack");
            Add(table,"aiden_q","slow");
            Add(table,"aiden_w","slow");
            Add(table,"aiden_w","root");
            Add(table,"aiden_r","slow");
            Add(table,"aiden_r","stun");
            Add(table,"echion_q","slow");
            Add(table,"elena_r","freeze");
            Add(table,"johann_q","root");
            Add(table,"johann_w","slow");
            Add(table,"johann_e","slow");
            Add(table,"william_w","slow");
            Add(table,"william_w","stun");
            Add(table,"william_w","knockback");
            Add(table,"william_r","slow");
            Add(table,"irem_w","slow");
            Add(table,"eva_w","slow");
            Add(table,"eva_w","airborne");
            Add(table,"eva_e","slow");
            Add(table,"ian_q","root");
            Add(table,"ian_r","fear");
            Add(table,"eleven_q","slow");
            Add(table,"eleven_w","taunt");
            Add(table,"eleven_e","knockback");
            Add(table,"zahir_e","airborne");
            Add(table,"jenny_w","slow");
            Add(table,"jenny_r","slow");
            Add(table,"camilo_e","knockback");
            Add(table,"camilo_r","stun");
            Add(table,"karla_w","slow");
            Add(table,"karla_r","slow");
            Add(table,"karla_r","stun");
            Add(table,"cathy_w","slow");
            Add(table,"cathy_e","root");
            Add(table,"cathy_e","stun");
            Add(table,"chloe_q","slow");
            Add(table,"chloe_w","slow");
            Add(table,"chloe_w","airborne");
            Add(table,"chiara_e","root", timing:"mania");
            Add(table,"tazia_q","knockback");
            Add(table,"tazia_w","stun");
            Add(table,"tazia_e","slow");
            Add(table,"tazia_r","slow");
            Add(table,"theodore_e","slow");
            Add(table,"theodore_e","root");
            Add(table,"felix_q","airborne", need:"weaving", count:2);
            Add(table,"felix_w","root", need:"weaving", count:2);
            Add(table,"felix_r","stun");
            Add(table,"priya_q","knockback");
            Add(table,"priya_w","slow");
            Add(table,"priya_e","slow");
            Add(table,"priya_e","root");
            Add(table,"priya_r","dance", timing:"echo");
            Add(table,"fiora_q","slow");
            Add(table,"fiora_r","slow");
            Add(table,"fiora_r","stun", timing:"fleche");
            Add(table,"piolo_q","slow");
            Add(table,"piolo_e","airborne");
            Add(table,"piolo_e","knockback");
            Add(table,"hart_q","slow");
            Add(table,"haze_w","stun");
            Add(table,"haze_r","slow");
            Add(table,"debi_marlene_e","slow");
            Add(table,"debi_marlene_e","airborne", need:"stance", count:0, exact:true);
            Add(table,"debi_marlene_r","stun");
            Add(table,"debi_marlene_r","pull");
            Add(table,"arda_w","slow");
            Add(table,"arda_w","stun", timing:"cube");
            Add(table,"arda_e","knockback");
            Add(table,"abigail_r","slow", timing:"dimension");
            Add(table,"alonso_q","stun", timing:"next_basic");
            Add(table,"alonso_e","root", timing:"attraction");
            Add(table,"alonso_r","slow");
            Add(table,"alonso_r","pull");
            Add(table,"leni_q","knockback");
            Add(table,"leni_w","slow");
            Add(table,"leni_e","stun");
            Add(table,"leni_r","slow");
            Add(table,"tsubame_q","slow");
            Add(table,"kenneth_q","airborne");
            Add(table,"kenneth_r","stun");
            Add(table,"kenneth_r","airborne");
            Add(table,"katja_e","slow");
            Add(table,"darko_w","slow");
            Add(table,"darko_w","attack_down");
            Add(table,"darko_e","airborne");
            Add(table,"darko_r","suppression");
            Add(table,"darko_r","slow");
            Add(table,"lenore_w","root");
            Add(table,"lenore_e","slow");
            Add(table,"lenore_r","slow", timing:"recital");
            Add(table,"lenore_r","berserk", timing:"finale");
            Add(table,"garnet_q","slow");
            Add(table,"garnet_e","stun");
            Add(table,"garnet_r","root");
            Add(table,"yumin_w","slow");
            Add(table,"yumin_w","knockback");
            Add(table,"yumin_r","slow");
            Add(table,"yumin_r","airborne", timing:"crane");
            Add(table,"hisui_q","slow");
            Add(table,"hisui_w","airborne", need:"iaido", count:2);
            Add(table,"hisui_r","slow");
            Add(table,"justyna_q","slow");
            Add(table,"justyna_w","slow");
            Add(table,"istvan_q","slow");
            Add(table,"istvan_e","airborne", need:"variable", count:2);
            Add(table,"istvan_e","armor_break");
            Add(table,"istvan_r","slow");
            Add(table,"xuelin_w","slow");
            Add(table,"xuelin_e","slow");
            Add(table,"xuelin_r","slow");
            Add(table,"henry_w","slow");
            Add(table,"henry_e","root", need:"chronograph", count:1);
            Add(table,"henry_r","slow");
            Add(table,"henry_r","stun", timing:"chrono_explosion");
            Add(table,"blair_e","slow");
            Add(table,"mirka_q","slow");
            Add(table,"mirka_q","stun", need:"impulse", count:4);
            Add(table,"mirka_e","knockback");
            Add(table,"mirka_r","airborne", timing:"downburst");
            Add(table,"fenrir_q","slow", need:"claw", count:2);
            Add(table,"fenrir_w","pull");
            Add(table,"fenrir_r","slow", timing:"fatal_bite");
            Add(table,"coraline_q","slow", need:"mirror", count:1);
            Add(table,"coraline_e","root");
            Add(table,"bihyung_w","slow");
            Add(table,"bihyung_e","taunt");
            Add(table,"bihyung_r","slow");
            Add(table,"craver_q","slow");
            Add(table,"craver_w","slow");
            Add(table,"craver_w","airborne");
            Add(table,"lucia_q","slow", need:"glorious", count:1);
            Add(table,"lucia_r","stun", need:"crystal", count:1);
            Add(table,"ceres_q","stun", need:"rush", count:1);
            Add(table,"ceres_w","slow");
            Add(table,"ceres_w","knockback");
            Add(table,"garnet_w","slow", timing:"pain_release");
            Add(table,"garnet_w","root", need:"pain", count:3, timing:"charged_pain");
            Add(table,"weapon_bow","slow");
            Add(table,"weapon_hammer","armor_break");
            Add(table,"weapon_dagger","slow");
            Add(table,"nathapon_r","stasis");
            Add(table,"martina_q","slow", need:"camera", count:1);
            Add(table,"martina_q","root", need:"camera", count:1);
            var broadcastRoot=table["martina_q"].Last();broadcastRoot.conditionKey2="record";broadcastRoot.conditionAmount2=3;
            Add(table,"emma_r","root",need:"dove",previous:"emma_q");
            Add(table,"emma_r","pull",need:"hat",previous:"emma_w");
            Add(table,"emma_r","polymorph",need:"rabbit",previous:"emma_e");
            Add(table,"emma_r","slow",need:"rabbit",previous:"emma_e");
            Add(table,"elena_q","freeze",need:"chill",count:2);
            Add(table,"elena_w","freeze",need:"chill",count:2);
            Add(table,"tia_q","silence",need:"brush",count:0,exact:true);
            var tia_q_0_2=table["tia_q"].Last();tia_q_0_2.conditionKey2="paint";tia_q_0_2.conditionAmount2=2;tia_q_0_2.conditionExact2=true;
            Add(table,"tia_q","silence",need:"brush",count:1,exact:true);
            var tia_q_1_1=table["tia_q"].Last();tia_q_1_1.conditionKey2="paint";tia_q_1_1.conditionAmount2=1;tia_q_1_1.conditionExact2=true;
            Add(table,"tia_q","root",need:"brush",count:2,exact:true);
            var tia_q_2_1=table["tia_q"].Last();tia_q_2_1.conditionKey2="paint";tia_q_2_1.conditionAmount2=1;tia_q_2_1.conditionExact2=true;
            Add(table,"tia_q","root",need:"brush",count:0,exact:true);
            var tia_q_0_3=table["tia_q"].Last();tia_q_0_3.conditionKey2="paint";tia_q_0_3.conditionAmount2=3;tia_q_0_3.conditionExact2=true;
            Add(table,"tia_e","silence",need:"brush",count:0,exact:true);
            var tia_e_0_2=table["tia_e"].Last();tia_e_0_2.conditionKey2="paint";tia_e_0_2.conditionAmount2=2;tia_e_0_2.conditionExact2=true;
            Add(table,"tia_e","silence",need:"brush",count:1,exact:true);
            var tia_e_1_1=table["tia_e"].Last();tia_e_1_1.conditionKey2="paint";tia_e_1_1.conditionAmount2=1;tia_e_1_1.conditionExact2=true;
            Add(table,"tia_e","root",need:"brush",count:2,exact:true);
            var tia_e_2_1=table["tia_e"].Last();tia_e_2_1.conditionKey2="paint";tia_e_2_1.conditionAmount2=1;tia_e_2_1.conditionExact2=true;
            Add(table,"tia_e","root",need:"brush",count:0,exact:true);
            var tia_e_0_3=table["tia_e"].Last();tia_e_0_3.conditionKey2="paint";tia_e_0_3.conditionAmount2=3;tia_e_0_3.conditionExact2=true;
            var movement=new HashSet<string>(new[] { "jackie_q","jackie_e","aya_e","hyunwoo_e","yuki_e","hyejin_e","sua_e","emma_r","charlotte_e","nicky_w","nicky_r","daniel_e","daniel_r","tia_e","laura_q","laura_e","leon_e","leon_r","rozzi_q","rozzi_e","luke_q","luke_e","luke_r","dailin_q","rio_e","martina_e","mai_e","markus_e","markus_r","magnus_r","bianca_e","shoichi_w","silvia_w","adriana_e","isaac_q","jan_e","estelle_e","aiden_e","aiden_r","echion_e","elena_w","william_r","irem_r","jenny_e","camilo_w","cathy_q","cathy_r","chloe_w","felix_q","felix_w","fiora_e","piolo_r","haze_e","abigail_e","alonso_e","leni_w","kenneth_e","darko_e","garnet_e","yumin_e","hisui_e","justyna_e","justyna_r","istvan_q","istvan_w","istvan_e","istvan_r","xuelin_e","henry_e","mirka_w","mirka_e","mirka_r","fenrir_r","bihyung_r","craver_e","craver_r","lucia_e","ceres_q","ceres_e","weapon_dagger","weapon_axe","weapon_sword","weapon_rapier","tactical_blink","tactical_plasma" });
            foreach(var card in cards)
            {
                if(card.category!="basic"){card.weak=0;card.vulnerable=0;}
                List<CardStatusRule> rules;card.statuses=table.TryGetValue(card.id,out rules)?rules.ToArray():new CardStatusRule[0];
                card.movement=movement.Contains(card.id);
            }
        }
        static void Add(Dictionary<string,List<CardStatusRule>> table,string card,string kind,string need=null,int count=1,bool exact=false,string timing="cast",string previous=null)
        {
            List<CardStatusRule> rules;if(!table.TryGetValue(card,out rules)){rules=new List<CardStatusRule>();table.Add(card,rules);}
            rules.Add(new CardStatusRule {key=kind,onHit=timing=="cast",duration=1,conditionKey=need,conditionAmount=count,conditionExact=exact,timing=timing,conditionPrevious=previous});
        }
    }
}
